### ISSUE TITLE
Compilation issue with mafExtractor

### ISSUE THREAD

**Issue by urjaswita** [dentearl/mafTools#15]
Hi, I am getting an error while compiling mafExtractor:

$ sudo make all
clang -std=c99 -stdlib=libstdc++ -O3 -c -O3 -Wall -Werror --pedantic -funroll-loops -DNDEBUG -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -I ../../sonLib/lib -I ../inc -I ../external  src/mafExtractorAPI.c -o src/mafExtractorAPI.o.tmp -lm
clang: error: -lm: 'linker' input unused [-Werror,-Wunused-command-line-argument]
make: *** [src/mafExtractorAPI.o] Error 1

Rest of the components compiled fine. Could you please help me fix this? Thanks so much. I am on MacOS-X Sierra.

**Comment by dentearl** [comment]
In mafExtractor/Makefile, 
change line 25 to be 
${cxx} ${cflags} -O3 $< ${API} -o $@.tmp

change line 30 to be
${cxx} ${cflags} -g -O0 $< ${testAPI} -o $@.tmp

change line 34 to be 
${cxx} -O3 -c ${cflags} $< -o $@.tmp

I think that should get you there, let me know.
