### ISSUE TITLE
mafExtractor would split MSA even they should be together

### ISSUE THREAD

**Issue by zy041225** [dentearl/mafTools#17]
Hi,

I'm dealing with my MSA using mafExtractor, but some output is split into two or more alignments when they should be one.

For example, when running the following command
`mafExtractor --maf chrX.nonoverlap.maf --seq "hsap.chrX" --start 100067347 --stop 100067714 > split/chrX.nonoverlap.maf.100067347-100067714.maf`

one of the MSA
[origin.txt](https://github.com/dentearl/mafTools/files/1491243/origin.txt)

are split into multiple parts
[split.txt](https://github.com/dentearl/mafTools/files/1491269/split.txt)

and if I add `--soft`, it output the same alignment as input without extraction

Please check.

**Comment by dentearl** [comment]
I'm pretty sure it's doing the right thing here. The sequence you asked for, hsap.chrX, has gaps in it. mafExtractor only cares about that sequence so any insertions are left out.

**Comment by zy041225** [comment]
Thanks for the explanation. BTW, will mafExtractor check if there's any gap in reference only?

**Comment by dentearl** [comment]
Right, it walks the reference and pulls out all blocks that contain the
reference and cuts blocks that lack the reference.
