### ISSUE TITLE
compilation fails -Werror=format-overflow=

### ISSUE THREAD

**Issue by paula-tataru** [dentearl/mafTools#22]
Hi,

I am trying to compile mafTools and I get the following output:
mafTools$ make
cd lib && make all
make[1]: Entering directory '/mnt/c/Users/tatarup/tools/mafTools/lib'
gcc -O3 -c -std=c99 -O3 -Wextra -Wall -Werror -pedantic -I ../external/ -I ../inc/ common.c -o common.o.tmp
mv common.o.tmp common.o
gcc -O3 -c -std=c99 -O3 -Wextra -Wall -Werror -pedantic -I ../external/ -I ../inc/ sharedMaf.c -o sharedMaf.o.tmp -lm
sharedMaf.c: In function ‘maf_mafBlock_print’:
sharedMaf.c:1037:22: error: ‘%lu’ directive writing between 1 and 19 bytes into a region of size 7 [-Werror=format-overflow=]
     sprintf(fmtName, " %%-%"PRIu64"s", maxName + 2);
                      ^~~~~~~
sharedMaf.c:1037:27: note: format string is defined here
     sprintf(fmtName, " %%-%"PRIu64"s", maxName + 2);
sharedMaf.c:1037:22: note: directive argument in the range [3, 9223372036854775808]
     sprintf(fmtName, " %%-%"PRIu64"s", maxName + 2);
                      ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from sharedMaf.c:31:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 6 and 24 bytes into a destination of size 10
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:28: recipe for target 'sharedMaf.o' failed
make[1]: *** [sharedMaf.o] Error 1
make[1]: Leaving directory '/mnt/c/Users/tatarup/tools/mafTools/lib'
Makefile:41: recipe for target 'lib.all' failed
make: *** [lib.all] Error 2

Any idea what's going on and how I can get this to work?

Thanks,
Paula

**Comment by paula-tataru** [comment]
I fixed this by changing `char fmtName[10]` to `char fmtName[30]` in _sharedMaf.c_, line 1011. Similar errors occur afterwards which can be fixed the same way.

**Comment by MaoYafei** [comment]
Hi all,

I had the same issue as Tataru. Then, I edited the c file as Tataru did. However, I still get another error like below 'mkdir -p ../bin/
gcc -std=c99 -Wno-unused-but-set-variable -O3 -Wall -Werror --pedantic -funroll-loops -DNDEBUG -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -I ../../sonLib/lib -I ../inc -I ../external  -O3 src/mafExtractor.c ../lib/common.o ../lib/sharedMaf.o ../external/CuTest.a src/mafExtractorAPI.o src/buildVersion.o -o ../bin/mafExtractor.tmp
../lib/sharedMaf.o: In function `maf_mafBlock_print':
sharedMaf.c:(.text+0x2104): undefined reference to `log10'
sharedMaf.c:(.text+0x2133): undefined reference to `log10'
sharedMaf.c:(.text+0x2162): undefined reference to `log10'
collect2: error: ld returned 1 exit status
make[1]: *** [../bin/mafExtractor] Error 1'

do you have any idea about it?

Thank you.

Best,
Yafei
