### ISSUE TITLE
ERROR: testSonLibKVTokyoCabinet (kvdbTest.TestCase)

### ISSUE THREAD

**Issue by sjin09** [dentearl/mafTools#9]
Dear Benedict,

I am trying to compile sonLib for mafTools and I have get this one error "ERROR: testSonLibKVTokyoCabinet (kvdbTest.TestCase)"

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sonLib/kvdbTest.py", line 18, in testSonLibKVTokyoCabinet
    system("sonLib_kvDatabaseTest --type=tokyocabinet")
  File "/usr/local/lib/python2.7/site-packages/sonLib/bioio.py", line 184, in system
    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
RuntimeError: Command: sonLib_kvDatabaseTest --type=tokyocabinet exited with non-zero status 128

Do I require the TokyoCabinet to run this test? and is it okay to let this error go by for the mafTools? What do you guys recommend?

Yours faithfully,
Jin

**Comment by dentearl** [comment]
You want to open this issue against sonLib. Ben should fix this (if he hasn't already).
